---
title: "01_"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Load Packages, warning=FALSE}
library(dplyr)
library(elo)
library(lubridate)
library(fitzRoy)
```

```{r Import fitzRoy data}
stats <- get_afltables_stats(start_date = "2017-01-01", end_date = "2019-12-01")
```


```{r Manipulate}

# Make round column numeric (removes finals)
stats_manip <- stats %>% mutate(Round = as.numeric(Round))
```

```{r Keys}
# DT scoring system
dfs_kick <- 3
dfs_mark <- 3
dfs_hb <- 2
dfs_ho <- 1
dfs_fa <- -3 
dfs_ff <- 1
dfs_goal <- 6
dfs_behind <- 1
dfs_tackle <- 4

# Team Disposals
team_disp <- tibble(team = c("Carlton", "Collingwood", "St Kilda", "Sydney", "Essendon", "Gold Coast", "North Melbourne",                               "Adelaide", "Fremantle", "Richmond", "Western Bulldogs", "Hawthorn", "Greater Western Sydney",                              "Brisbane Lions", "West Coast", "Geelong", "Melbourne", "Port Adelaide"), 
                    team_disp = c(347, 399.2, 388.7, 371.7, 381.6, 339.9, 367.9, 383, 363.1, 366.8, 387.6, 376.5, 377.9, 373.5,                              356.1, 380.1, 386.2, 375.5))
```

```{r Create new variables: Durability, Form, Talent, Team Role}

# create player id
stats_manip <- stats_manip %>% mutate(player_id = paste(First.name, Surname, ID, sep = ""))


# add DT scores
stats_manip <- 
  stats_manip %>%
  mutate(k_dfs = Kicks * dfs_kick,
         hb_dfs = Handballs * dfs_hb,
         mark_dfs = Marks * dfs_mark,
         tackle_dfs = Tackles * dfs_tackle,
         ho_dfs = Hit.Outs * dfs_ho,
         fa_dfs = Frees.Against * dfs_fa,
         ff_dfs = Frees.For * dfs_ff,
         goal_dfs = Goals * dfs_goal,
         behind_dfs = Behinds * dfs_behind) %>%
  mutate(dfs_score = k_dfs + hb_dfs + mark_dfs + tackle_dfs + ho_dfs + fa_dfs + ff_dfs + goal_dfs + behind_dfs)


# create player season averages
averages <- 
  stats_manip %>%
  filter(Season == 2019 & Round < 24) %>%
  group_by(player_id, Playing.for) %>%
  summarise(games_played = n(),
            dt_avg       = round(mean(dfs_score)),
            disp_avg     = round(mean(Kicks + Handballs))) %>%
  mutate(durability      = round((games_played / 22) * 100))


# create form (last 12 avg)
form <- 
  stats_manip %>%
  filter(Season == 2019 & Round >= 12 & Round < 24) %>%
  group_by(player_id) %>%
  summarise(last_12     = mean(dfs_score)) 


# create talent (highest previous 3 year average)
talent <- 
  stats_manip %>%
  filter(Round <24) %>%
  group_by(player_id, Season) %>%
  summarise(highest_avg   = mean(dfs_score)) %>%
  group_by(player_id) %>%
  mutate(talent          = max(highest_avg)) %>%
  filter(Season == 2019)
 
# create team_role (% of disp of team disposals - using as a proxy for role in team)
combined <- left_join(averages, team_disp, by = c("Playing.for" = "team" ))

combined <- 
  combined %>%
  mutate(team_role      = (disp_avg / team_disp) * 100)


# add form and talent to averages tibble
combined <- 
  merge(combined, talent, by = "player_id", all = TRUE) 

combined <- 
  merge(combined, form, by = "player_id", all = TRUE)


# remove unnessacary variables
combined <- 
  combined %>%
  select(-c(5,7,9,10))
```

```{r Create Player Ranking Model}
# Standardize and weight each variable

# Look at excel how I standardized

```

```{r Find middle MAGIC number}
# find magic number of 2017, 2018, 2019 seasons
# find magic number of projction
# use magic number to multiple prpjection to get DT score


```

```{r Add subjective injuries adjustment}
# manually add injury adjustments

# take 10% of all injury adjumsents (as they are for SC)
```


```{r Create Ranking and ADP for positions}
# look at how Pitty put positions into df

```

